#!/usr/bin/env bash

#
# Copyright 2015-2019 by Kevin L. Goodwin [fwmechanic@gmail.com]; All rights reserved
#
# This file is part of K.
#
# K is free software: you can redistribute it and/or modify it under the
# terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# K is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along
# with K.  If not, see <http://www.gnu.org/licenses/>.
#

die() { printf %s "${@+$@$'\n'}" 1>&2 ; exit 1 ; }

export LC_ALL="en_US.utf8"  # fix `grep -P`
num_rand_tags=50  # test param

tagfnm=tags
first_tag="$(head -n 1 "$tagfnm" | cut -f 1)"
last_tag="$(tail -n 1 "$tagfnm" | cut -f 1)"
before_first="${first_tag%?}"  # remove last char of first_tag  https://unix.stackexchange.com/a/259042
after_last="${last_tag}_nonexistent"

tgtexe="${1:?}"

make "$tgtexe" || die

chk_tagfind() {
   local ans ; ans="$(grep --count -P '^\Q'"$1"'\E\t' "$tagfnm")"
   # echo "$1: expect $ans"
   local lc ; lc="$(./"$tgtexe" "$1" | wc -l)" ; ((lc==ans)) || die "FAIL: for T=$1, expected $ans, got $lc"
   }
chk_tagfind "$before_first"
chk_tagfind "$first_tag"
chk_tagfind "$last_tag"
chk_tagfind "$after_last"

readarray -t test_tags <<<"$( cut -f 1 "$tagfnm" | sort -u | sort -R | head -n "$num_rand_tags" )"  # https://unix.stackexchange.com/a/322505
# echo "${test_tags[@]}"

for tag in "${test_tags[@]}"; do
   #echo "tag=$tag'"
   chk_tagfind "$tag"
done

chk_tagged_files() {
   local file_tag_field ; file_tag_field=$'\t'"kind:file"
   local ref ; ref="$(grep -P "$file_tag_field"'(\t|$)' tags | cut -f2 | sort -u | wc -l)"
   local tst ; tst="$(./"$tgtexe" "$file_tag_field" | wc -l)"
   ((tst==ref)) || die "FAIL: chk_tagged_files, expected $ref, got $lc"
   }

chk_tagged_files
