module(...)

   local cmk_globalvars = {             -- "oh, the humanity!"  (or: "the abomination known as CMake")
      -- https://cmake.org/cmake/help/latest/manual/cmake-variables.7.html
      -- following variables are fixed symbols defined by CMake which do not bear a "CMAKE_" prefix (and thus offer no clues as to their origin)
      BUILD_SHARED_LIBS=true, CACHE=true, ENV=true, EXECUTABLE_OUTPUT_PATH=true, LIBRARY_OUTPUT_PATH=true,

      PROJECT_BINARY_DIR=true, PROJECT_DESCRIPTION=true, PROJECT_HOMEPAGE_URL=true,        -- NB: these have analogs prefixed by project name
      PROJECT_NAME=true, PROJECT_SOURCE_DIR=true, PROJECT_VERSION=true,                    --     see cmk_autovar_pats elsewhere
      PROJECT_VERSION_MAJOR=true, PROJECT_VERSION_MINOR=true, PROJECT_VERSION_PATCH=true,
      PROJECT_VERSION_TWEAK=true,

      -- a large number of these are 'current-build-tool' indicators which may be defined by many tools aside from CMake
      ANDROID=true, APPLE=true, BORLAND=true, CYGWIN=true, ["GHS-MULTI"]=true, IOS=true, MINGW=true,
      MSVC=true, MSVC10=true, MSVC11=true, MSVC12=true, MSVC14=true, MSVC60=true, MSVC70=true,
      MSVC71=true, MSVC80=true, MSVC90=true, MSVC_IDE=true, MSVC_TOOLSET_VERSION=true,
      MSVC_VERSION=true, MSYS=true, UNIX=true, WIN32=true, WINCE=true, WINDOWS_PHONE=true,
      WINDOWS_STORE=true, XCODE=true, XCODE_VERSION=true,
      }  -- still need to figure out what to do with these {being a new category: tagless-tags?}: perform a CMake man-page web-search?
   function globalvar( tag )
      if tag:match '^CMAKE_' or cmk_globalvars[tag] then
         return tag, user.URL_CMake_docs
         end
      end

   local cmk_full_identifier = {
      -- Command names from https://cmake.org/cmake/help/latest/manual/cmake-commands.7.html
      -- These commands are always available.
      ['break']                                            =true,
      cmake_host_system_information                        =true,
      cmake_minimum_required                               =true,
      cmake_parse_arguments                                =true,
      cmake_policy                                         =true,
      configure_file                                       =true,
      continue                                             =true,
      ['else']                                             =true,
      ['elseif']                                           =true,
      endforeach                                           =true,
      endfunction                                          =true,
      endif                                                =true,
      endmacro                                             =true,
      endwhile                                             =true,
      execute_process                                      =true,
      file                                                 =true,
      find_file                                            =true,
      find_library                                         =true,
      find_package                                         =true,
      find_path                                            =true,
      find_program                                         =true,
      foreach                                              =true,
      ['function']                                         =true,
      get_cmake_property                                   =true,
      get_directory_property                               =true,
      get_filename_component                               =true,
      get_property                                         =true,
      ['if']                                               =true,
      include                                              =true,
      include_guard                                        =true,
      list                                                 =true,
      macro                                                =true,
      mark_as_advanced                                     =true,
      math                                                 =true,
      message                                              =true,
      option                                               =true,
      ['return']                                           =true,
      separate_arguments                                   =true,
      set                                                  =true,
      set_directory_properties                             =true,
      set_property                                         =true,
      site_name                                            =true,
      string                                               =true,
      unset                                                =true,
      variable_watch                                       =true,
      ['while']                                            =true,

      -- Project Commands - These commands are available only in CMake projects.
      add_compile_definitions                              =true,
      add_compile_options                                  =true,
      add_custom_command                                   =true,
      add_custom_target                                    =true,
      add_definitions                                      =true,
      add_dependencies                                     =true,
      add_executable                                       =true,
      add_library                                          =true,
      add_link_options                                     =true,
      add_subdirectory                                     =true,
      add_test                                             =true,
      aux_source_directory                                 =true,
      build_command                                        =true,
      create_test_sourcelist                               =true,
      define_property                                      =true,
      enable_language                                      =true,
      enable_testing                                       =true,
      export                                               =true,
      fltk_wrap_ui                                         =true,
      get_source_file_property                             =true,
      get_target_property                                  =true,
      get_test_property                                    =true,
      include_directories                                  =true,
      include_external_msproject                           =true,
      include_regular_expression                           =true,
      install                                              =true,
      link_directories                                     =true,
      link_libraries                                       =true,
      load_cache                                           =true,
      project                                              =true,
      remove_definitions                                   =true,
      set_source_files_properties                          =true,
      set_target_properties                                =true,
      set_tests_properties                                 =true,
      source_group                                         =true,
      target_compile_definitions                           =true,
      target_compile_features                              =true,
      target_compile_options                               =true,
      target_include_directories                           =true,
      target_link_directories                              =true,
      target_link_libraries                                =true,
      target_link_options                                  =true,
      target_sources                                       =true,
      try_compile                                          =true,
      try_run                                              =true,

      -- CTest Commands - These commands are available only in CTest scripts.
      ctest_build                                          =true,
      ctest_configure                                      =true,
      ctest_coverage                                       =true,
      ctest_empty_binary_directory                         =true,
      ctest_memcheck                                       =true,
      ctest_read_custom_files                              =true,
      ctest_run_script                                     =true,
      ctest_sleep                                          =true,
      ctest_start                                          =true,
      ctest_submit                                         =true,
      ctest_test                                           =true,
      ctest_update                                         =true,
      ctest_upload                                         =true,

      -- Property names  from https://cmake.org/cmake/help/latest/manual/cmake-properties.7.html
      -- I may regret doing this (since these tend to be present only in
      --   set_property, set_directory_property, get_property, get_directory_property and similar
      -- command parameter lists), but:
      -- CMake recognizes "properties" having certain names which have no particular obvious relationship to CMake.
      -- Property names with variable components have been elided since (a) they are very legacy (bad practice), (b)
      -- hopefully not present in the crap I have to work with, and (c) detection requires linear pattern match
      -- traversal of all  (I'm not yet willing to trade away the performance).

      -- Properties of Global Scope
      ALLOW_DUPLICATE_CUSTOM_TARGETS                       =true,
      AUTOGEN_SOURCE_GROUP                                 =true,
      AUTOGEN_TARGETS_FOLDER                               =true,
      AUTOMOC_SOURCE_GROUP                                 =true,
      AUTOMOC_TARGETS_FOLDER                               =true,
      AUTORCC_SOURCE_GROUP                                 =true,
      CMAKE_C_KNOWN_FEATURES                               =true,
      CMAKE_CXX_KNOWN_FEATURES                             =true,
      CMAKE_ROLE                                           =true,
      DEBUG_CONFIGURATIONS                                 =true,
      DISABLED_FEATURES                                    =true,
      ENABLED_FEATURES                                     =true,
      ENABLED_LANGUAGES                                    =true,
      FIND_LIBRARY_USE_LIB32_PATHS                         =true,
      FIND_LIBRARY_USE_LIB64_PATHS                         =true,
      FIND_LIBRARY_USE_LIBX32_PATHS                        =true,
      FIND_LIBRARY_USE_OPENBSD_VERSIONING                  =true,
      GENERATOR_IS_MULTI_CONFIG                            =true,
      GLOBAL_DEPENDS_DEBUG_MODE                            =true,
      GLOBAL_DEPENDS_NO_CYCLES                             =true,
      IN_TRY_COMPILE                                       =true,
      PACKAGES_FOUND                                       =true,
      PACKAGES_NOT_FOUND                                   =true,
      JOB_POOLS                                            =true,
      PREDEFINED_TARGETS_FOLDER                            =true,
      ECLIPSE_EXTRA_NATURES                                =true,
      ECLIPSE_EXTRA_CPROJECT_CONTENTS                      =true,
      REPORT_UNDEFINED_PROPERTIES                          =true,
      RULE_LAUNCH_COMPILE                                  =true,
      RULE_LAUNCH_CUSTOM                                   =true,
      RULE_LAUNCH_LINK                                     =true,
      RULE_MESSAGES                                        =true,
      TARGET_ARCHIVES_MAY_BE_SHARED_LIBS                   =true,
      TARGET_MESSAGES                                      =true,
      TARGET_SUPPORTS_SHARED_LIBS                          =true,
      USE_FOLDERS                                          =true,
      XCODE_EMIT_EFFECTIVE_PLATFORM_NAME                   =true,

      -- Properties on Directories
      ADDITIONAL_CLEAN_FILES                               =true,
      ADDITIONAL_MAKE_CLEAN_FILES                          =true,
      BINARY_DIR                                           =true,
      BUILDSYSTEM_TARGETS                                  =true,
      CACHE_VARIABLES                                      =true,
      CLEAN_NO_CUSTOM                                      =true,
      CMAKE_CONFIGURE_DEPENDS                              =true,
      COMPILE_DEFINITIONS                                  =true,
      COMPILE_OPTIONS                                      =true,
      DEFINITIONS                                          =true,
      EXCLUDE_FROM_ALL                                     =true,
      IMPLICIT_DEPENDS_INCLUDE_TRANSFORM                   =true,
      INCLUDE_DIRECTORIES                                  =true,
      INCLUDE_REGULAR_EXPRESSION                           =true,
      INTERPROCEDURAL_OPTIMIZATION                         =true,
      LABELS                                               =true,
      LINK_DIRECTORIES                                     =true,
      LINK_OPTIONS                                         =true,
      LISTFILE_STACK                                       =true,
      MACROS                                               =true,
      PARENT_DIRECTORY                                     =true,
      RULE_LAUNCH_COMPILE                                  =true,
      RULE_LAUNCH_CUSTOM                                   =true,
      RULE_LAUNCH_LINK                                     =true,
      SOURCE_DIR                                           =true,
      SUBDIRECTORIES                                       =true,
      TESTS                                                =true,
      TEST_INCLUDE_FILES                                   =true,
      VARIABLES                                            =true,
      VS_STARTUP_PROJECT                                   =true,

      -- Properties on Targets
      ADDITIONAL_CLEAN_FILES                               =true,
      ALIASED_TARGET                                       =true,
      ANDROID_ANT_ADDITIONAL_OPTIONS                       =true,
      ANDROID_API                                          =true,
      ANDROID_API_MIN                                      =true,
      ANDROID_ARCH                                         =true,
      ANDROID_ASSETS_DIRECTORIES                           =true,
      ANDROID_GUI                                          =true,
      ANDROID_JAR_DEPENDENCIES                             =true,
      ANDROID_JAR_DIRECTORIES                              =true,
      ANDROID_JAVA_SOURCE_DIR                              =true,
      ANDROID_NATIVE_LIB_DEPENDENCIES                      =true,
      ANDROID_NATIVE_LIB_DIRECTORIES                       =true,
      ANDROID_PROCESS_MAX                                  =true,
      ANDROID_PROGUARD                                     =true,
      ANDROID_PROGUARD_CONFIG_PATH                         =true,
      ANDROID_SECURE_PROPS_PATH                            =true,
      ANDROID_SKIP_ANT_STEP                                =true,
      ANDROID_STL_TYPE                                     =true,
      ARCHIVE_OUTPUT_DIRECTORY                             =true,
      ARCHIVE_OUTPUT_NAME                                  =true,
      AUTOGEN_BUILD_DIR                                    =true,
      AUTOGEN_ORIGIN_DEPENDS                               =true,
      AUTOGEN_PARALLEL                                     =true,
      AUTOGEN_TARGET_DEPENDS                               =true,
      AUTOMOC_COMPILER_PREDEFINES                          =true,
      AUTOMOC_DEPEND_FILTERS                               =true,
      AUTOMOC_EXECUTABLE                                   =true,
      AUTOMOC_MACRO_NAMES                                  =true,
      AUTOMOC_MOC_OPTIONS                                  =true,
      AUTOMOC                                              =true,
      AUTOUIC                                              =true,
      AUTOUIC_EXECUTABLE                                   =true,
      AUTOUIC_OPTIONS                                      =true,
      AUTOUIC_SEARCH_PATHS                                 =true,
      AUTORCC                                              =true,
      AUTORCC_EXECUTABLE                                   =true,
      AUTORCC_OPTIONS                                      =true,
      BINARY_DIR                                           =true,
      BUILD_RPATH                                          =true,
      BUILD_RPATH_USE_ORIGIN                               =true,
      BUILD_WITH_INSTALL_NAME_DIR                          =true,
      BUILD_WITH_INSTALL_RPATH                             =true,
      BUNDLE_EXTENSION                                     =true,
      BUNDLE                                               =true,
      C_EXTENSIONS                                         =true,
      C_STANDARD                                           =true,
      C_STANDARD_REQUIRED                                  =true,
      COMMON_LANGUAGE_RUNTIME                              =true,
      COMPATIBLE_INTERFACE_BOOL                            =true,
      COMPATIBLE_INTERFACE_NUMBER_MAX                      =true,
      COMPATIBLE_INTERFACE_NUMBER_MIN                      =true,
      COMPATIBLE_INTERFACE_STRING                          =true,
      COMPILE_DEFINITIONS                                  =true,
      COMPILE_FEATURES                                     =true,
      COMPILE_FLAGS                                        =true,
      COMPILE_OPTIONS                                      =true,
      COMPILE_PDB_NAME                                     =true,
      COMPILE_PDB_OUTPUT_DIRECTORY                         =true,
      CROSSCOMPILING_EMULATOR                              =true,
      CUDA_PTX_COMPILATION                                 =true,
      CUDA_SEPARABLE_COMPILATION                           =true,
      CUDA_RESOLVE_DEVICE_SYMBOLS                          =true,
      CUDA_EXTENSIONS                                      =true,
      CUDA_STANDARD                                        =true,
      CUDA_STANDARD_REQUIRED                               =true,
      CXX_EXTENSIONS                                       =true,
      CXX_STANDARD                                         =true,
      CXX_STANDARD_REQUIRED                                =true,
      DEBUG_POSTFIX                                        =true,
      DEFINE_SYMBOL                                        =true,
      DEPLOYMENT_REMOTE_DIRECTORY                          =true,
      DEPLOYMENT_ADDITIONAL_FILES                          =true,
      DOTNET_TARGET_FRAMEWORK_VERSION                      =true,
      EchoString                                           =true,
      ENABLE_EXPORTS                                       =true,
      EXCLUDE_FROM_ALL                                     =true,
      EXCLUDE_FROM_DEFAULT_BUILD                           =true,
      EXPORT_NAME                                          =true,
      EXPORT_PROPERTIES                                    =true,
      FOLDER                                               =true,
      Fortran_FORMAT                                       =true,
      Fortran_MODULE_DIRECTORY                             =true,
      FRAMEWORK                                            =true,
      FRAMEWORK_VERSION                                    =true,
      GENERATOR_FILE_NAME                                  =true,
      GHS_INTEGRITY_APP                                    =true,
      GHS_NO_SOURCE_GROUP_FILE                             =true,
      GNUtoMS                                              =true,
      HAS_CXX                                              =true,
      IMPLICIT_DEPENDS_INCLUDE_TRANSFORM                   =true,
      IMPORTED_COMMON_LANGUAGE_RUNTIME                     =true,
      IMPORTED_CONFIGURATIONS                              =true,
      IMPORTED_GLOBAL                                      =true,
      IMPORTED_IMPLIB                                      =true,
      IMPORTED_LIBNAME                                     =true,
      IMPORTED_LINK_DEPENDENT_LIBRARIES                    =true,
      IMPORTED_LINK_INTERFACE_LANGUAGES                    =true,
      IMPORTED_LINK_INTERFACE_LIBRARIES                    =true,
      IMPORTED_LINK_INTERFACE_MULTIPLICITY                 =true,
      IMPORTED_LOCATION                                    =true,
      IMPORTED_NO_SONAME                                   =true,
      IMPORTED_OBJECTS                                     =true,
      IMPORTED                                             =true,
      IMPORTED_SONAME                                      =true,
      IMPORT_PREFIX                                        =true,
      IMPORT_SUFFIX                                        =true,
      INCLUDE_DIRECTORIES                                  =true,
      INSTALL_NAME_DIR                                     =true,
      INSTALL_RPATH                                        =true,
      INSTALL_RPATH_USE_LINK_PATH                          =true,
      INTERFACE_AUTOUIC_OPTIONS                            =true,
      INTERFACE_COMPILE_DEFINITIONS                        =true,
      INTERFACE_COMPILE_FEATURES                           =true,
      INTERFACE_COMPILE_OPTIONS                            =true,
      INTERFACE_INCLUDE_DIRECTORIES                        =true,
      INTERFACE_LINK_DEPENDS                               =true,
      INTERFACE_LINK_DIRECTORIES                           =true,
      INTERFACE_LINK_LIBRARIES                             =true,
      INTERFACE_LINK_OPTIONS                               =true,
      INTERFACE_POSITION_INDEPENDENT_CODE                  =true,
      INTERFACE_SOURCES                                    =true,
      INTERFACE_SYSTEM_INCLUDE_DIRECTORIES                 =true,
      INTERPROCEDURAL_OPTIMIZATION                         =true,
      IOS_INSTALL_COMBINED                                 =true,
      JOB_POOL_COMPILE                                     =true,
      JOB_POOL_LINK                                        =true,
      LABELS                                               =true,
      LIBRARY_OUTPUT_DIRECTORY                             =true,
      LIBRARY_OUTPUT_NAME                                  =true,
      LINK_DEPENDS_NO_SHARED                               =true,
      LINK_DEPENDS                                         =true,
      LINKER_LANGUAGE                                      =true,
      LINK_DIRECTORIES                                     =true,
      LINK_FLAGS                                           =true,
      LINK_INTERFACE_LIBRARIES                             =true,
      LINK_INTERFACE_MULTIPLICITY                          =true,
      LINK_LIBRARIES                                       =true,
      LINK_OPTIONS                                         =true,
      LINK_SEARCH_END_STATIC                               =true,
      LINK_SEARCH_START_STATIC                             =true,
      LINK_WHAT_YOU_USE                                    =true,
      LOCATION                                             =true,
      MACOSX_BUNDLE_INFO_PLIST                             =true,
      MACOSX_BUNDLE                                        =true,
      MACOSX_FRAMEWORK_INFO_PLIST                          =true,
      MACOSX_RPATH                                         =true,
      MANUALLY_ADDED_DEPENDENCIES                          =true,
      MSVC_RUNTIME_LIBRARY                                 =true,
      NAME                                                 =true,
      NO_SONAME                                            =true,
      NO_SYSTEM_FROM_IMPORTED                              =true,
      OSX_ARCHITECTURES                                    =true,
      OUTPUT_NAME                                          =true,
      PDB_NAME                                             =true,
      PDB_OUTPUT_DIRECTORY                                 =true,
      POSITION_INDEPENDENT_CODE                            =true,
      PREFIX                                               =true,
      PRIVATE_HEADER                                       =true,
      PROJECT_LABEL                                        =true,
      PUBLIC_HEADER                                        =true,
      RESOURCE                                             =true,
      RULE_LAUNCH_COMPILE                                  =true,
      RULE_LAUNCH_CUSTOM                                   =true,
      RULE_LAUNCH_LINK                                     =true,
      RUNTIME_OUTPUT_DIRECTORY                             =true,
      RUNTIME_OUTPUT_NAME                                  =true,
      SKIP_BUILD_RPATH                                     =true,
      SOURCE_DIR                                           =true,
      SOURCES                                              =true,
      SOVERSION                                            =true,
      STATIC_LIBRARY_FLAGS                                 =true,
      STATIC_LIBRARY_OPTIONS                               =true,
      SUFFIX                                               =true,
      Swift_DEPENDENCIES_FILE                              =true,
      Swift_MODULE_DIRECTORY                               =true,
      Swift_MODULE_NAME                                    =true,
      TYPE                                                 =true,
      VERSION                                              =true,
      VISIBILITY_INLINES_HIDDEN                            =true,
      VS_CONFIGURATION_TYPE                                =true,
      VS_DEBUGGER_COMMAND                                  =true,
      VS_DEBUGGER_COMMAND_ARGUMENTS                        =true,
      VS_DEBUGGER_ENVIRONMENT                              =true,
      VS_DEBUGGER_WORKING_DIRECTORY                        =true,
      VS_DESKTOP_EXTENSIONS_VERSION                        =true,
      VS_DOTNET_REFERENCES                                 =true,
      VS_DOTNET_REFERENCES_COPY_LOCAL                      =true,
      VS_DOTNET_TARGET_FRAMEWORK_VERSION                   =true,
      VS_GLOBAL_KEYWORD                                    =true,
      VS_GLOBAL_PROJECT_TYPES                              =true,
      VS_GLOBAL_ROOTNAMESPACE                              =true,
      VS_IOT_EXTENSIONS_VERSION                            =true,
      VS_IOT_STARTUP_TASK                                  =true,
      VS_JUST_MY_CODE_DEBUGGING                            =true,
      VS_KEYWORD                                           =true,
      VS_MOBILE_EXTENSIONS_VERSION                         =true,
      VS_NO_SOLUTION_DEPLOY                                =true,
      VS_PACKAGE_REFERENCES                                =true,
      VS_PROJECT_IMPORT                                    =true,
      VS_SCC_AUXPATH                                       =true,
      VS_SCC_LOCALPATH                                     =true,
      VS_SCC_PROJECTNAME                                   =true,
      VS_SCC_PROVIDER                                      =true,
      VS_SDK_REFERENCES                                    =true,
      VS_USER_PROPS                                        =true,
      VS_WINDOWS_TARGET_PLATFORM_MIN_VERSION               =true,
      VS_WINRT_COMPONENT                                   =true,
      VS_WINRT_EXTENSIONS                                  =true,
      VS_WINRT_REFERENCES                                  =true,
      WIN32_EXECUTABLE                                     =true,
      WINDOWS_EXPORT_ALL_SYMBOLS                           =true,
      XCODE_EXPLICIT_FILE_TYPE                             =true,
      XCODE_GENERATE_SCHEME                                =true,
      XCODE_PRODUCT_TYPE                                   =true,
      XCODE_SCHEME_ADDRESS_SANITIZER                       =true,
      XCODE_SCHEME_ADDRESS_SANITIZER_USE_AFTER_RETURN      =true,
      XCODE_SCHEME_ARGUMENTS                               =true,
      XCODE_SCHEME_DEBUG_AS_ROOT                           =true,
      XCODE_SCHEME_DISABLE_MAIN_THREAD_CHECKER             =true,
      XCODE_SCHEME_DYNAMIC_LIBRARY_LOADS                   =true,
      XCODE_SCHEME_DYNAMIC_LINKER_API_USAGE                =true,
      XCODE_SCHEME_ENVIRONMENT                             =true,
      XCODE_SCHEME_EXECUTABLE                              =true,
      XCODE_SCHEME_GUARD_MALLOC                            =true,
      XCODE_SCHEME_MAIN_THREAD_CHECKER_STOP                =true,
      XCODE_SCHEME_MALLOC_GUARD_EDGES                      =true,
      XCODE_SCHEME_MALLOC_SCRIBBLE                         =true,
      XCODE_SCHEME_MALLOC_STACK                            =true,
      XCODE_SCHEME_THREAD_SANITIZER                        =true,
      XCODE_SCHEME_THREAD_SANITIZER_STOP                   =true,
      XCODE_SCHEME_UNDEFINED_BEHAVIOUR_SANITIZER           =true,
      XCODE_SCHEME_UNDEFINED_BEHAVIOUR_SANITIZER_STOP      =true,
      XCODE_SCHEME_ZOMBIE_OBJECTS                          =true,
      XCTEST                                               =true,

      -- Properties on Tests
      ATTACHED_FILES_ON_FAIL                               =true,
      ATTACHED_FILES                                       =true,
      COST                                                 =true,
      DEPENDS                                              =true,
      DISABLED                                             =true,
      ENVIRONMENT                                          =true,
      FAIL_REGULAR_EXPRESSION                              =true,
      FIXTURES_CLEANUP                                     =true,
      FIXTURES_REQUIRED                                    =true,
      FIXTURES_SETUP                                       =true,
      LABELS                                               =true,
      MEASUREMENT                                          =true,
      PASS_REGULAR_EXPRESSION                              =true,
      PROCESSOR_AFFINITY                                   =true,
      PROCESSORS                                           =true,
      REQUIRED_FILES                                       =true,
      RESOURCE_LOCK                                        =true,
      RUN_SERIAL                                           =true,
      SKIP_RETURN_CODE                                     =true,
      TIMEOUT                                              =true,
      TIMEOUT_AFTER_MATCH                                  =true,
      WILL_FAIL                                            =true,
      WORKING_DIRECTORY                                    =true,

      -- Properties on Source Files
      ABSTRACT                                             =true,
      AUTOUIC_OPTIONS                                      =true,
      AUTORCC_OPTIONS                                      =true,
      COMPILE_DEFINITIONS                                  =true,
      COMPILE_FLAGS                                        =true,
      COMPILE_OPTIONS                                      =true,
      EXTERNAL_OBJECT                                      =true,
      Fortran_FORMAT                                       =true,
      GENERATED                                            =true,
      HEADER_FILE_ONLY                                     =true,
      INCLUDE_DIRECTORIES                                  =true,
      KEEP_EXTENSION                                       =true,
      LABELS                                               =true,
      LANGUAGE                                             =true,
      LOCATION                                             =true,
      MACOSX_PACKAGE_LOCATION                              =true,
      OBJECT_DEPENDS                                       =true,
      OBJECT_OUTPUTS                                       =true,
      SKIP_AUTOGEN                                         =true,
      SKIP_AUTOMOC                                         =true,
      SKIP_AUTORCC                                         =true,
      SKIP_AUTOUIC                                         =true,
      Swift_DEPENDENCIES_FILE                              =true,
      Swift_DIAGNOSTICS_FILE                               =true,
      SYMBOLIC                                             =true,
      VS_COPY_TO_OUT_DIR                                   =true,
      VS_DEPLOYMENT_CONTENT                                =true,
      VS_DEPLOYMENT_LOCATION                               =true,
      VS_INCLUDE_IN_VSIX                                   =true,
      VS_RESOURCE_GENERATOR                                =true,
      VS_SHADER_DISABLE_OPTIMIZATIONS                      =true,
      VS_SHADER_ENABLE_DEBUG                               =true,
      VS_SHADER_ENTRYPOINT                                 =true,
      VS_SHADER_FLAGS                                      =true,
      VS_SHADER_MODEL                                      =true,
      VS_SHADER_OBJECT_FILE_NAME                           =true,
      VS_SHADER_OUTPUT_HEADER_FILE                         =true,
      VS_SHADER_TYPE                                       =true,
      VS_SHADER_VARIABLE_NAME                              =true,
      VS_TOOL_OVERRIDE                                     =true,
      VS_XAML_TYPE                                         =true,
      WRAP_EXCLUDE                                         =true,
      XCODE_EXPLICIT_FILE_TYPE                             =true,
      XCODE_FILE_ATTRIBUTES                                =true,
      XCODE_LAST_KNOWN_FILE_TYPE                           =true,

      -- Properties on Cache Entries
      ADVANCED                                             =true,
      HELPSTRING                                           =true,
      MODIFIED                                             =true,
      STRINGS                                              =true,
      TYPE                                                 =true,
      VALUE                                                =true,

      -- Deprecated Properties on Directories
      TEST_INCLUDE_FILE                                    =true,
      -- Deprecated Properties on Targets
      POST_INSTALL_SCRIPT                                  =true,
      PRE_INSTALL_SCRIPT                                   =true,
      -- Deprecated Properties on Source Files
      }
   function ident( tag )
      if cmk_full_identifier[tag] then
         return tag, user.URL_CMake_docs
         end
      end

   local cmk_pjnm_pat = '([%a%d_][%a%d_%-]+)'
   local cmk_autovar_pats = {           -- "oh, the humanity!"  (or: "the abomination known as CMake")
      cmk_pjnm_pat..'_SOURCE_DIR'    ,  -- these variables are auto-vivified (into the global namespace?)
      cmk_pjnm_pat..'_BINARY_DIR'    ,  -- by CMake when command 'project(projnm_pat)' is executed.
      cmk_pjnm_pat..'_VERSION'       ,
      cmk_pjnm_pat..'_VERSION_MAJOR' ,  -- Yes, such 19th-century behavior is SHOCKING & INFURIATING to
      cmk_pjnm_pat..'_VERSION_MINOR' ,  -- anyone with a moderately tuned sense of progamming-language
      cmk_pjnm_pat..'_VERSION_PATCH' ,  -- right and wrong...
      cmk_pjnm_pat..'_VERSION_TWEAK' ,
      cmk_pjnm_pat..'_DESCRIPTION'   ,
      cmk_pjnm_pat..'_HOMEPAGE_URL'  ,
      }
   function proj_autovar( tag )  -- https://cmake.org/cmake/help/latest/command/project.html
      if not tag:match '^PROJECT_' then  -- tags matching this pattern are left to hit globalvar
         for _,pat in ipairs(cmk_autovar_pats) do
            local proj = tag:match( pat )
            if proj then return proj end
            end
         end
      end
